# Generated by Django 4.1.3 on 2022-11-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceList',
            new_name='Attendance',
        ),
    ]
