# Generated by Django 4.1.3 on 2022-11-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_attendancelist_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
