# Generated by Django 4.1.3 on 2022-11-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='machine_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
