# Generated by Django 4.1.3 on 2022-11-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_machine_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['id']},
        ),
    ]
